name: Build Packages

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        sdk:
          - openwrt-24.10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Packages
        uses: sbwml/openwrt-gh-action-sdk@go1.25
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-mosdns-panel
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.sdk }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Upload packages
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          prerelease: false
          artifacts: "bin/packages/${{ matrix.arch }}/packages_ci/*.ipk"

  package-config:
    name: Package Config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip Config
        run: |
          timestamp=$(date +%Y%m%d%H%M)
          zip -r mosdns_custom_config_${timestamp}.zip yaml/
          echo "CONFIG_ZIP=mosdns_custom_config_${timestamp}.zip" >> $GITHUB_ENV

      - name: Upload Config Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mosdns-custom-config
          path: ${{ env.CONFIG_ZIP }}

      - name: Upload Config to Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          prerelease: false
          artifacts: ${{ env.CONFIG_ZIP }}
